from code_generation.quantity import NanoAODQuantity

run = NanoAODQuantity("run")
luminosityBlock = NanoAODQuantity("luminosityBlock")
event = NanoAODQuantity("event")
LHE_Njets = NanoAODQuantity("LHE_Njets")
prefireWeight = NanoAODQuantity("L1PreFiringWeight_Nom")

nLHEPdfWeight = NanoAODQuantity("nLHEPdfWeight")
LHEPdfWeight = NanoAODQuantity("LHEPdfWeight")
nLHEScaleWeight = NanoAODQuantity("nLHEScaleWeight")
LHEScaleWeight = NanoAODQuantity("LHEScaleWeight")

Tau_pt = NanoAODQuantity("Tau_pt")
Tau_eta = NanoAODQuantity("Tau_eta")
Tau_phi = NanoAODQuantity("Tau_phi")
Tau_mass = NanoAODQuantity("Tau_mass")
Tau_dz = NanoAODQuantity("Tau_dz")
Tau_dxy = NanoAODQuantity("Tau_dxy")
Tau_charge = NanoAODQuantity("Tau_charge")
Tau_decayMode = NanoAODQuantity("Tau_decayMode")
Tau_genMatch = NanoAODQuantity("Tau_genPartFlav")
Tau_IDraw = NanoAODQuantity("Tau_rawDeepTau2017v2p1VSjet")
Tau_indexToGen = NanoAODQuantity("Tau_genPartIdx")
Tau_associatedJet = NanoAODQuantity("Tau_jetIdx")
Tau_ID_vsJet = NanoAODQuantity("Tau_idDeepTau2017v2p1VSjet")
Tau_ID_vsEle = NanoAODQuantity("Tau_idDeepTau2017v2p1VSe")
Tau_ID_vsMu = NanoAODQuantity("Tau_idDeepTau2017v2p1VSmu")

Muon_pt = NanoAODQuantity("Muon_pt")
Muon_eta = NanoAODQuantity("Muon_eta")
Muon_phi = NanoAODQuantity("Muon_phi")
Muon_mass = NanoAODQuantity("Muon_mass")
Muon_iso = NanoAODQuantity("Muon_pfRelIso04_all")
Muon_dz = NanoAODQuantity("Muon_dz")
Muon_dxy = NanoAODQuantity("Muon_dxy")
Muon_charge = NanoAODQuantity("Muon_charge")
Muon_genMatch = NanoAODQuantity("Muon_genPartFlav")
Muon_indexToGen = NanoAODQuantity("Muon_genPartIdx")

Muon_dxybs = NanoAODQuantity("Muon_dxybs")
Muon_miniPFRelIso_chg = NanoAODQuantity("Muon_miniPFRelIso_chg")
Muon_mvaLowPt = NanoAODQuantity("Muon_mvaLowPt")
Muon_pfRelIso03_all = NanoAODQuantity("Muon_pfRelIso03_all")
Muon_pfRelIso03_chg = NanoAODQuantity("Muon_pfRelIso03_chg")
Muon_pfRelIso04_all = NanoAODQuantity("Muon_pfRelIso04_all")
Muon_ptErr = NanoAODQuantity("Muon_ptErr")
Muon_segmentComp = NanoAODQuantity("Muon_segmentComp")
Muon_softMva = NanoAODQuantity("Muon_softMva")
Muon_tkRelIso = NanoAODQuantity("Muon_tkRelIso")
Muon_tunepRelPt = NanoAODQuantity("Muon_tunepRelPt")

Muon_fsrPhotonIdx = NanoAODQuantity("Muon_fsrPhotonIdx")
Muon_genPartIdx = NanoAODQuantity("Muon_genPartIdx")
Muon_highPtId = NanoAODQuantity("Muon_highPtId")
Muon_miniIsoId = NanoAODQuantity("Muon_miniIsoId")
Muon_multiIsoId = NanoAODQuantity("Muon_multiIsoId")
# Muon_mvaId = NanoAODQuantity("Muon_mvaId")
# Muon_mvaLowPtId = NanoAODQuantity("Muon_mvaLowPtId")
Muon_nStations = NanoAODQuantity("Muon_nStations")
Muon_nTrackerLayers = NanoAODQuantity("Muon_nTrackerLayers")
Muon_pfIsoId = NanoAODQuantity("Muon_pfIsoId")
Muon_puppiIsoId = NanoAODQuantity("Muon_puppiIsoId")
Muon_tkIsoId = NanoAODQuantity("Muon_tkIsoId")

Muon_dxyErr = NanoAODQuantity("Muon_dxyErr")
Muon_dzErr = NanoAODQuantity("Muon_dzErr")
Muon_ip3d = NanoAODQuantity("Muon_ip3d")
Muon_isPFcand = NanoAODQuantity("Muon_isPFcand")
Muon_jetIdx = NanoAODQuantity("Muon_jetIdx")
Muon_jetNDauCharged = NanoAODQuantity("Muon_jetNDauCharged")
Muon_jetPtRelv2 = NanoAODQuantity("Muon_jetPtRelv2")
Muon_jetRelIso = NanoAODQuantity("Muon_jetRelIso")
Muon_miniPFRelIso_all = NanoAODQuantity("Muon_miniPFRelIso_all")
Muon_mvaTTH = NanoAODQuantity("Muon_mvaTTH")
Muon_sip3d = NanoAODQuantity("Muon_sip3d")
Muon_tightCharge = NanoAODQuantity("Muon_tightCharge")
Muon_softMvaId = NanoAODQuantity("Muon_softMvaId")

Muon_highPurity = NanoAODQuantity("Muon_highPurity")
Muon_inTimeMuon = NanoAODQuantity("Muon_inTimeMuon")
Muon_isGlobal = NanoAODQuantity("Muon_isGlobal")
Muon_isStandalone = NanoAODQuantity("Muon_isStandalone")
Muon_isTracker = NanoAODQuantity("Muon_isTracker")
Muon_looseId = NanoAODQuantity("Muon_looseId")
Muon_mediumId = NanoAODQuantity("Muon_mediumId")
Muon_mediumPromptId = NanoAODQuantity("Muon_mediumPromptId")
Muon_softId = NanoAODQuantity("Muon_softId")
Muon_tightId = NanoAODQuantity("Muon_tightId")
Muon_triggerIdLoose = NanoAODQuantity("Muon_triggerIdLoose")

Muon_normalizedChi2 = NanoAODQuantity("Muon_normalizedChi2")
Muon_numberOfValidPixelHits = NanoAODQuantity("Muon_numberOfValidPixelHits")
Muon_numberOfValidMuonHits = NanoAODQuantity("Muon_numberOfValidMuonHits")

HLT_IsoMu24 = NanoAODQuantity("HLT_IsoMu24")
HLT_Ele27_WPTight_Gsf = NanoAODQuantity("HLT_Ele27_WPTight_Gsf")
HLT_Ele28_WPTight_Gsf = NanoAODQuantity("HLT_Ele28_WPTight_Gsf")

Electron_pt = NanoAODQuantity("Electron_pt")
Electron_eta = NanoAODQuantity("Electron_eta")
Electron_dxy = NanoAODQuantity("Electron_dxy")
Electron_dxyErr = NanoAODQuantity("Electron_dxyErr")
Electron_dz = NanoAODQuantity("Electron_dz")
Electron_dzErr = NanoAODQuantity("Electron_dzErr")
Electron_phi = NanoAODQuantity("Electron_phi")
Electron_mass = NanoAODQuantity("Electron_mass")
Electron_iso = NanoAODQuantity("Electron_pfRelIso03_all")
Electron_charge = NanoAODQuantity("Electron_charge")
Electron_genMatch = NanoAODQuantity("Electron_genPartFlav")
Electron_indexToGen = NanoAODQuantity("Electron_genPartIdx")

Electron_dEscaleDown = NanoAODQuantity("Electron_dEscaleDown")
Electron_dEscaleUp = NanoAODQuantity("Electron_dEscaleUp")
Electron_dEsigmaDown = NanoAODQuantity("Electron_dEsigmaDown")
Electron_dEsigmaUp = NanoAODQuantity("Electron_dEsigmaUp")
Electron_deltaEtaSC = NanoAODQuantity("Electron_deltaEtaSC")
Electron_dr03EcalRecHitSumEt = NanoAODQuantity("Electron_dr03EcalRecHitSumEt")
Electron_dr03HcalDepth1TowerSumEt = NanoAODQuantity("Electron_dr03HcalDepth1TowerSumEt")
Electron_dr03TkSumPt =NanoAODQuantity("Electron_dr03TkSumPt")
Electron_dr03TkSumPtHEEP = NanoAODQuantity("Electron_dr03TkSumPtHEEP")
Electron_eCorr = NanoAODQuantity("Electron_eCorr")
Electron_eInvMinusPInv = NanoAODQuantity("Electron_eInvMinusPInv")
Electron_energyErr = NanoAODQuantity("Electron_energyErr")
Electron_hoe = NanoAODQuantity("Electron_hoe")
Electron_ip3d = NanoAODQuantity("Electron_ip3d")
Electron_jetPtRelv2 = NanoAODQuantity("Electron_jetPtRelv2")
Electron_jetRelIso = NanoAODQuantity("Electron_jetRelIso")
Electron_miniPFRelIso_all = NanoAODQuantity("Electron_miniPFRelIso_all")
Electron_mvaFall17V2Iso = NanoAODQuantity("Electron_mvaFall17V2Iso")
Electron_mvaFall17V2noIso = NanoAODQuantity("Electron_mvaFall17V2noIso")
Electron_mvaTTH = NanoAODQuantity("Electron_mvaTTH")
Electron_pfRelIso03_all = NanoAODQuantity("Electron_pfRelIso03_all")
Electron_pfRelIso03_chg = NanoAODQuantity("Electron_pfRelIso03_chg")
Electron_r9 = NanoAODQuantity("Electron_r9")
Electron_scEtOverPt = NanoAODQuantity("Electron_scEtOverPt")
Electron_sieie = NanoAODQuantity("Electron_sieie")
Electron_sip3d = NanoAODQuantity("Electron_sip3d")

Electron_dEtaInSeed = NanoAODQuantity("Electron_dEtaInSeed")
Electron_deltaEtaSuperClusterTrackAtVtx = NanoAODQuantity("Electron_deltaEtaSuperClusterTrackAtVtx")
Electron_deltaPhiSuperClusterTrackAtVtx = NanoAODQuantity("Electron_deltaPhiSuperClusterTrackAtVtx")

Electron_cutBased = NanoAODQuantity("Electron_cutBased")
Electron_jetIdx = NanoAODQuantity("Electron_jetIdx")
Electron_photonIdx = NanoAODQuantity("Electron_photonIdx")
Electron_tightCharge = NanoAODQuantity("Electron_tightCharge")
Electron_vidNestedWPBitmap = NanoAODQuantity("Electron_vidNestedWPBitmap")
Electron_vidNestedWPBitmapHEEP = NanoAODQuantity("Electron_vidNestedWPBitmapHEEP")

Electron_convVeto = NanoAODQuantity("Electron_convVeto")
Electron_cutBased_HEEP = NanoAODQuantity("Electron_cutBased_HEEP")
Electron_isPFcand = NanoAODQuantity("Electron_isPFcand")
Electron_mvaFall17V2Iso_WP80 = NanoAODQuantity("Electron_mvaFall17V2Iso_WP80")
Electron_mvaFall17V2Iso_WP90 = NanoAODQuantity("Electron_mvaFall17V2Iso_WP90")
Electron_mvaFall17V2Iso_WPL = NanoAODQuantity("Electron_mvaFall17V2Iso_WPL")
Electron_mvaFall17V2noIso_WP80 = NanoAODQuantity("Electron_mvaFall17V2noIso_WP80")
Electron_mvaFall17V2noIso_WP90 = NanoAODQuantity("Electron_mvaFall17V2noIso_WP90")
Electron_mvaFall17V2noIso_WPL = NanoAODQuantity("Electron_mvaFall17V2noIso_WPL")

Electron_jetNDauCharged = NanoAODQuantity("Electron_jetNDauCharged")
Electron_lostHits = NanoAODQuantity("Electron_lostHits")
Electron_seedGain = NanoAODQuantity("Electron_seedGain")


GenJet_pt = NanoAODQuantity("GenJet_pt")
GenJet_eta = NanoAODQuantity("GenJet_eta")
GenJet_phi = NanoAODQuantity("GenJet_phi")

Jet_eta = NanoAODQuantity("Jet_eta")
Jet_phi = NanoAODQuantity("Jet_phi")
Jet_pt = NanoAODQuantity("Jet_pt")
Jet_mass = NanoAODQuantity("Jet_mass")
Jet_area = NanoAODQuantity("Jet_area")
Jet_rawFactor = NanoAODQuantity("Jet_rawFactor")
Jet_ID = NanoAODQuantity("Jet_jetId")
Jet_PUID = NanoAODQuantity("Jet_puId")
Jet_associatedGenJet = NanoAODQuantity("Jet_genJetIdx")
BJet_discriminator = NanoAODQuantity("Jet_btagDeepFlavB")

SoftActivityJetHT = NanoAODQuantity("SoftActivityJetHT")
SoftActivityJetHT10 = NanoAODQuantity("SoftActivityJetHT10")
SoftActivityJetHT2 = NanoAODQuantity("SoftActivityJetHT2")
SoftActivityJetHT5 = NanoAODQuantity("SoftActivityJetHT5")
SoftActivityJetNjets10 = NanoAODQuantity("SoftActivityJetNjets10")
SoftActivityJetNjets2 = NanoAODQuantity("SoftActivityJetNjets2")
SoftActivityJetNjets5 = NanoAODQuantity("SoftActivityJetNjets5")

Pileup_nTrueInt = NanoAODQuantity("Pileup_nTrueInt")
#npv = NanoAODQuantity("PV_npvs")
npv_good = NanoAODQuantity("PV_npvsGood")
rho = NanoAODQuantity("Rho_fixedGridRhoFastjetAll")
rho_fastjet_central_charged_pileup = NanoAODQuantity("Rho_fixedGridRhoFastjetCentralChargedPileUp")
rho_fastjet_central_calo = NanoAODQuantity("Rho_fixedGridRhoFastjetCentralCalo")
PSWeight = NanoAODQuantity("PSWeight")
nPSWeight = NanoAODQuantity("nPSWeight")

GenParticle_eta = NanoAODQuantity("GenPart_eta")
GenParticle_phi = NanoAODQuantity("GenPart_phi")
GenParticle_pt = NanoAODQuantity("GenPart_pt")
GenParticle_mass = NanoAODQuantity("GenPart_mass")
GenParticle_pdgId = NanoAODQuantity("GenPart_pdgId")
GenParticle_status = NanoAODQuantity("GenPart_status")
GenParticle_statusFlags = NanoAODQuantity("GenPart_statusFlags")
GenParticle_motherid = NanoAODQuantity("GenPart_genPartIdxMother")

GenDressedLepton_eta = NanoAODQuantity("GenDressedLepton_eta")
GenDressedLepton_hasTauAnc = NanoAODQuantity("GenDressedLepton_hasTauAnc")
GenDressedLepton_mass = NanoAODQuantity("GenDressedLepton_mass")
GenDressedLepton_pdgId = NanoAODQuantity("GenDressedLepton_pdgId")
GenDressedLepton_phi = NanoAODQuantity("GenDressedLepton_phi")
GenDressedLepton_pt = NanoAODQuantity("GenDressedLepton_pt")

## Trigger Objects
TriggerObject_bit = NanoAODQuantity("TrigObj_filterBits")
TriggerObject_pt = NanoAODQuantity("TrigObj_pt")
TriggerObject_eta = NanoAODQuantity("TrigObj_eta")
TriggerObject_phi = NanoAODQuantity("TrigObj_phi")
TriggerObject_id = NanoAODQuantity("TrigObj_id")

## HTXS quantities
HTXS_Higgs_pt = NanoAODQuantity("HTXS_Higgs_pt")
HTXS_Higgs_y = NanoAODQuantity("HTXS_Higgs_y")
HTXS_njets30 = NanoAODQuantity("HTXS_njets30")
HTXS_stage_0 = NanoAODQuantity("HTXS_stage_0")
HTXS_stage_1_pTjet30 = NanoAODQuantity("HTXS_stage_1_pTjet30")
HTXS_stage1_1_fine_cat_pTjet30GeV = NanoAODQuantity("HTXS_stage1_1_fine_cat_pTjet30GeV")
HTXS_stage1_2_cat_pTjet30GeV = NanoAODQuantity("HTXS_stage1_2_cat_pTjet30GeV")
HTXS_stage1_2_fine_cat_pTjet30GeV = NanoAODQuantity("HTXS_stage1_2_fine_cat_pTjet30GeV")

## MET quantities
## TODO Swich to Puppi versions for METCOV and Signifiance as soon as they are in the nanoAOD
MET_covXX = NanoAODQuantity("MET_covXX")
MET_covXY = NanoAODQuantity("MET_covXY")
MET_covYY = NanoAODQuantity("MET_covYY")
MET_significance = NanoAODQuantity("MET_significance")

MET_phi = NanoAODQuantity("PuppiMET_phi")
MET_pt = NanoAODQuantity("PuppiMET_pt")
MET_sumEt = NanoAODQuantity("PuppiMET_sumEt")

PFMET_phi = NanoAODQuantity("MET_phi")
PFMET_pt = NanoAODQuantity("MET_pt")
PFMET_sumEt = NanoAODQuantity("MET_sumEt")

## Embedding Quantities
genWeight = NanoAODQuantity("genWeight")
TauEmbedding_initialMETEt = NanoAODQuantity("TauEmbedding_initialMETEt")
TauEmbedding_initialMETphi = NanoAODQuantity("TauEmbedding_initialMETphi")
TauEmbedding_initialPuppiMETEt = NanoAODQuantity("TauEmbedding_initialPuppiMETEt")
TauEmbedding_initialPuppiMETphi = NanoAODQuantity("TauEmbedding_initialPuppiMETphi")
TauEmbedding_isMediumLeadingMuon = NanoAODQuantity("TauEmbedding_isMediumLeadingMuon")
TauEmbedding_isMediumTrailingMuon = NanoAODQuantity("TauEmbedding_isMediumTrailingMuon")
TauEmbedding_isTightLeadingMuon = NanoAODQuantity("TauEmbedding_isTightLeadingMuon")
TauEmbedding_isTightTrailingMuon = NanoAODQuantity("TauEmbedding_isTightTrailingMuon")
TauEmbedding_InitialPairCandidates = NanoAODQuantity(
    "TauEmbedding_nInitialPairCandidates"
)
TauEmbedding_SelectionOldMass = NanoAODQuantity("TauEmbedding_SelectionOldMass")
TauEmbedding_SelectionNewMass = NanoAODQuantity("TauEmbedding_SelectionNewMass")
